feat: Adds internal pull-up R + auto race re-start after several seconds
jesuslg123/formula-led pull request #3
Opened 2019-11-06 20:46 UTC by jrierab

* feat: Adds internal pull-up resistors to the input pìns. The external resistors are not needed anymore.
* feat: Adds auto race re-start after several seconds

2019-11-09 08:34 UTC, jesuslg123 requested changes
Thank you so much for contributing! 💯 
Just a comment on the new added code.
:)

2019-11-09 08:34 UTC, jesuslg123 commented on LED_Race/LED_Race.ino
> +  pinMode(PLAYER2_PIN,INPUT_PULLUP);
I just realised that we were missing the `pinMode` setup and it was actually working :O 👍

2019-11-09 08:34 UTC, jesuslg123 commented on LED_Race/LED_Race.ino
> +    if (raceCountdown == 8) {
Nice idea. 
In order to avoid keep growing the `lopp` method, we could create a new method to restart the race and setup the race initial state again. This will allow us to have a self explanatory code and single responsibility functions.

2019-11-09 19:10 UTC, jrierab commented on LED_Race/LED_Race.ino
> +    if (raceCountdown == 8) {
:-) Just had done that 2 days ago, but forgot to push to remote :-(

2019-11-11 08:34 UTC, jesuslg123 approved these changes
Looks good! Thank you for contributing to the project :)

2019-11-11 08:34 UTC, merged